"""rework preferences: drop category lists, add workplace

Revision ID: 017211361cf9
Revises: 88fe6366ba92
Create Date: 2026-08-11 09:55:34.209390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '017211361cf9'
down_revision: Union[str, Sequence[str], None] = '88fe6366ba92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('workplace', sa.String(length=200), nullable=True))
    op.drop_column('user_preferences', 'preferred_categories')
    op.drop_column('user_preferences', 'disliked_categories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('disliked_categories', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('user_preferences', sa.Column('preferred_categories', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('user_preferences', 'workplace')
    # ### end Alembic commands ###
