"""add task lists and subtasks

Revision ID: 0a52c3d876fa
Revises: 15b9f6c97f15
Create Date: 2026-09-14 21:47:35.690773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a52c3d876fa'
down_revision: Union[str, Sequence[str], None] = '15b9f6c97f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_lists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_lists_tenant_id'), 'task_lists', ['tenant_id'], unique=False)
    op.add_column('tasks', sa.Column('list_id', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('parent_task_id', sa.UUID(), nullable=True))
    op.create_index('ix_tasks_list', 'tasks', ['list_id'], unique=False)
    op.create_index('ix_tasks_parent', 'tasks', ['parent_task_id'], unique=False)
    op.create_foreign_key(
        'fk_tasks_parent_task_id_tasks',
        'tasks', 'tasks', ['parent_task_id'], ['id'], ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_tasks_list_id_task_lists',
        'tasks', 'task_lists', ['list_id'], ['id'], ondelete='SET NULL',
    )
    op.create_check_constraint('ck_tasks_parent_not_self', 'tasks', 'parent_task_id IS NULL OR parent_task_id != id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_tasks_parent_not_self', 'tasks', type_='check')
    op.drop_constraint('fk_tasks_list_id_task_lists', 'tasks', type_='foreignkey')
    op.drop_constraint('fk_tasks_parent_task_id_tasks', 'tasks', type_='foreignkey')
    op.drop_index('ix_tasks_parent', table_name='tasks')
    op.drop_index('ix_tasks_list', table_name='tasks')
    op.drop_column('tasks', 'parent_task_id')
    op.drop_column('tasks', 'list_id')
    op.drop_index(op.f('ix_task_lists_tenant_id'), table_name='task_lists')
    op.drop_table('task_lists')
    # ### end Alembic commands ###
