"""add finance tables

Revision ID: 0e105c458199
Revises: e7721785e9b7
Create Date: 2026-08-16 15:27:23.371264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e105c458199'
down_revision: Union[str, Sequence[str], None] = 'e7721785e9b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_incomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_finance_incomes_amount_positive'),
    sa.CheckConstraint('payment_day >= 1 AND payment_day <= 31', name='ck_finance_incomes_payment_day_valid'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_incomes_tenant_id'), 'finance_incomes', ['tenant_id'], unique=False)
    op.create_index('ix_finance_incomes_tenant_user', 'finance_incomes', ['tenant_id', 'user_id'], unique=False)
    op.create_table('finance_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_day', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_finance_subscriptions_amount_positive'),
    sa.CheckConstraint('payment_day >= 1 AND payment_day <= 31', name='ck_finance_subscriptions_payment_day_valid'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finance_subscriptions_tenant_active', 'finance_subscriptions', ['tenant_id', 'active'], unique=False)
    op.create_index(op.f('ix_finance_subscriptions_tenant_id'), 'finance_subscriptions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_subscriptions_tenant_id'), table_name='finance_subscriptions')
    op.drop_index('ix_finance_subscriptions_tenant_active', table_name='finance_subscriptions')
    op.drop_table('finance_subscriptions')
    op.drop_index('ix_finance_incomes_tenant_user', table_name='finance_incomes')
    op.drop_index(op.f('ix_finance_incomes_tenant_id'), table_name='finance_incomes')
    op.drop_table('finance_incomes')
    # ### end Alembic commands ###
