"""add subscription kind

Revision ID: 152ef6e6b5e9
Revises: a9e12dfdaf57
Create Date: 2026-08-16 16:44:50.334974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '152ef6e6b5e9'
down_revision: Union[str, Sequence[str], None] = 'a9e12dfdaf57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - hand-adjusted: existing rows
    # need a default so the NOT NULL add doesn't fail (mirrors the cadence
    # column migration). ###
    kind_enum = sa.Enum('SUBSCRIPTION', 'RECURRING_EXPENSE', name='finance_subscription_kind')
    kind_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'finance_subscriptions',
        sa.Column(
            'kind',
            sa.Enum('SUBSCRIPTION', 'RECURRING_EXPENSE', name='finance_subscription_kind', create_type=False),
            nullable=False,
            server_default=sa.text("'SUBSCRIPTION'::finance_subscription_kind"),
        ),
    )
    op.alter_column('finance_subscriptions', 'kind', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finance_subscriptions', 'kind')
    sa.Enum(name='finance_subscription_kind').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
