"""add task budget fields

Revision ID: 15b9f6c97f15
Revises: bd03348c04e4
Create Date: 2026-08-16 18:33:20.009130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15b9f6c97f15'
down_revision: Union[str, Sequence[str], None] = 'bd03348c04e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('budget_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('tasks', sa.Column('budget_owner_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_tasks_budget_owner_user_id_users',
        'tasks', 'users', ['budget_owner_user_id'], ['id'], ondelete='SET NULL',
    )
    op.create_check_constraint('ck_tasks_budget_amount_positive', 'tasks', 'budget_amount IS NULL OR budget_amount > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_tasks_budget_amount_positive', 'tasks', type_='check')
    op.drop_constraint('fk_tasks_budget_owner_user_id_users', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'budget_owner_user_id')
    op.drop_column('tasks', 'budget_amount')
    # ### end Alembic commands ###
