"""add member invites

Revision ID: 64649f8490b6
Revises: 017211361cf9
Create Date: 2026-08-11 10:39:03.393236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '64649f8490b6'
down_revision: Union[str, Sequence[str], None] = '017211361cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column(
        'role',
        postgresql.ENUM('OWNER', 'MEMBER', name='user_role', create_type=False),
        nullable=False,
    ),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_invites_tenant_id'), 'member_invites', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_member_invites_token_hash'), 'member_invites', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_invites_token_hash'), table_name='member_invites')
    op.drop_index(op.f('ix_member_invites_tenant_id'), table_name='member_invites')
    op.drop_table('member_invites')
    # ### end Alembic commands ###
