"""add alice links

Revision ID: 88fe6366ba92
Revises: 98ac3d68d54a
Create Date: 2026-08-10 12:51:34.788922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88fe6366ba92'
down_revision: Union[str, Sequence[str], None] = '98ac3d68d54a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alice_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_alice_links_user_id')
    )
    op.create_index(op.f('ix_alice_links_tenant_id'), 'alice_links', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_alice_links_token_hash'), 'alice_links', ['token_hash'], unique=True)
    op.create_index(op.f('ix_alice_links_user_id'), 'alice_links', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alice_links_user_id'), table_name='alice_links')
    op.drop_index(op.f('ix_alice_links_token_hash'), table_name='alice_links')
    op.drop_index(op.f('ix_alice_links_tenant_id'), table_name='alice_links')
    op.drop_table('alice_links')
    # ### end Alembic commands ###
