"""add task order_index

Revision ID: 8b5b6158e663
Revises: 0a52c3d876fa
Create Date: 2026-09-14 22:22:37.484537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b5b6158e663'
down_revision: Union[str, Sequence[str], None] = '0a52c3d876fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('tasks', sa.Column('order_index', sa.Integer(), nullable=True))
    # Backfill existing rows so each sibling group (same tenant_id, list_id,
    # parent_task_id — NULLs included, PARTITION BY treats them as their own
    # group) gets a stable 0-based order matching its prior creation order.
    op.execute(
        """
        UPDATE tasks t
        SET order_index = sub.rn
        FROM (
            SELECT id, ROW_NUMBER() OVER (
                PARTITION BY tenant_id, list_id, parent_task_id ORDER BY created_at
            ) - 1 AS rn
            FROM tasks
        ) sub
        WHERE t.id = sub.id
        """
    )
    op.alter_column('tasks', 'order_index', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'order_index')
    # ### end Alembic commands ###
