"""add subscription cadence and payment month

Revision ID: a9e12dfdaf57
Revises: 0e105c458199
Create Date: 2026-08-16 16:05:51.495562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9e12dfdaf57'
down_revision: Union[str, Sequence[str], None] = '0e105c458199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - hand-adjusted: existing rows
    # (subscriptions already entered in prod before this migration) need a
    # default so the NOT NULL add doesn't fail. ###
    cadence_enum = sa.Enum('MONTHLY', 'YEARLY', name='finance_subscription_cadence')
    cadence_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'finance_subscriptions',
        sa.Column(
            'cadence',
            sa.Enum('MONTHLY', 'YEARLY', name='finance_subscription_cadence', create_type=False),
            nullable=False,
            server_default=sa.text("'MONTHLY'::finance_subscription_cadence"),
        ),
    )
    op.alter_column('finance_subscriptions', 'cadence', server_default=None)
    op.add_column('finance_subscriptions', sa.Column('payment_month', sa.Integer(), nullable=True))
    op.create_check_constraint('ck_finance_subscriptions_payment_month_matches_cadence', 'finance_subscriptions', "(cadence = 'MONTHLY' AND payment_month IS NULL) OR (cadence = 'YEARLY' AND payment_month BETWEEN 1 AND 12)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_finance_subscriptions_payment_month_matches_cadence', 'finance_subscriptions', type_='check')
    op.drop_column('finance_subscriptions', 'payment_month')
    op.drop_column('finance_subscriptions', 'cadence')
    sa.Enum(name='finance_subscription_cadence').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
