"""add user gender

Revision ID: bd03348c04e4
Revises: 152ef6e6b5e9
Create Date: 2026-08-16 17:05:49.658939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd03348c04e4'
down_revision: Union[str, Sequence[str], None] = '152ef6e6b5e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - hand-adjusted: create the enum
    # type explicitly first (mirrors the finance cadence/kind migrations). ###
    gender_enum = sa.Enum('MALE', 'FEMALE', name='user_gender')
    gender_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'users',
        sa.Column(
            'gender', sa.Enum('MALE', 'FEMALE', name='user_gender', create_type=False), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    sa.Enum(name='user_gender').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
