"""add calendar and preferences tables

Revision ID: f937a917fb17
Revises: 92688464149f
Create Date: 2026-08-10 13:57:26.502068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f937a917fb17'
down_revision: Union[str, Sequence[str], None] = '92688464149f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('WORKING_HOURS', 'SLEEP', 'MEETING', 'SPORT', 'TRIP', 'PERSONAL', 'UNAVAILABLE', name='calendar_event_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('recurrence', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_at >= start_at', name='ck_calendar_events_end_after_start'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_tenant_id'), 'calendar_events', ['tenant_id'], unique=False)
    op.create_index('ix_calendar_events_tenant_user_start', 'calendar_events', ['tenant_id', 'user_id', 'start_at'], unique=False)
    op.create_index(op.f('ix_calendar_events_user_id'), 'calendar_events', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('working_hours_start', sa.Time(), nullable=True),
    sa.Column('working_hours_end', sa.Time(), nullable=True),
    sa.Column('sleep_start', sa.Time(), nullable=True),
    sa.Column('sleep_end', sa.Time(), nullable=True),
    sa.Column('preferred_categories', sa.JSON(), nullable=False),
    sa.Column('disliked_categories', sa.JSON(), nullable=False),
    sa.Column('energy_pattern', sa.Enum('MORNING', 'EVENING', 'STEADY', name='energy_pattern'), nullable=False),
    sa.Column('task_speed_multiplier', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('task_speed_multiplier > 0', name='ck_user_preferences_speed_positive'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_preferences_user_id')
    )
    op.create_index(op.f('ix_user_preferences_tenant_id'), 'user_preferences', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_tenant_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_calendar_events_user_id'), table_name='calendar_events')
    op.drop_index('ix_calendar_events_tenant_user_start', table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_tenant_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    # ### end Alembic commands ###
